"""
Tools for the report agent to persist findings as JSON and HTML.
"""

import os
import json
from pathlib import Path
from datetime import date
import markdown as md


def _run_dir() -> Path:
    """Return the timestamped run directory set by main.py."""
    return Path(os.environ.get("REPORT_OUTPUT_DIR", "output"))


def save_json_report(findings_json: str) -> str:
    """
    Save the collected agent findings as output/report.json.

    Args:
        findings_json: JSON string containing findings from all specialist agents.

    Returns:
        Confirmation message with the saved file path.
    """
    try:
        data = json.loads(findings_json)
    except json.JSONDecodeError as e:
        return f"Error: invalid JSON — {e}"

    out = _run_dir() / "report.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(data, indent=2))
    return f"JSON report saved to {out.resolve()}"


def save_html_report(markdown_content: str) -> str:
    """
    Convert a Markdown report to a styled HTML file and save as output/report.html.

    Args:
        markdown_content: Full Markdown text of the cost optimization report.

    Returns:
        Confirmation message with the saved file path.
    """
    body = md.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "toc"],
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>AWS Cloud Cost Optimization Report — {date.today().isoformat()}</title>
<style>
  :root {{
    --bg: #0f172a; --card: #1e293b; --border: #334155;
    --text: #e2e8f0; --muted: #94a3b8;
    --accent: #38bdf8; --green: #4ade80; --yellow: #facc15;
    --red: #f87171; --purple: #c084fc;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: var(--bg); color: var(--text);
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 15px; line-height: 1.7; padding: 2rem;
  }}
  .container {{ max-width: 960px; margin: 0 auto; }}
  .banner {{
    background: linear-gradient(135deg, #1e3a5f 0%, #1e293b 100%);
    border: 1px solid var(--border); border-radius: 12px;
    padding: 1.5rem 2rem; margin-bottom: 2rem;
    display: flex; align-items: center; gap: 1rem;
  }}
  .banner-icon {{ font-size: 2rem; }}
  .banner h1 {{ font-size: 1.4rem; color: var(--accent); }}
  .banner p {{ color: var(--muted); font-size: 0.9rem; margin-top: 0.2rem; }}
  h1 {{ font-size: 1.8rem; color: var(--accent); margin: 1.5rem 0 0.75rem; }}
  h2 {{
    font-size: 1.2rem; color: var(--accent);
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.4rem; margin: 2rem 0 1rem;
  }}
  h3 {{ font-size: 1rem; color: var(--yellow); margin: 1.5rem 0 0.5rem; }}
  h4 {{ font-size: 0.95rem; color: var(--purple); margin: 1rem 0 0.4rem; }}
  p {{ margin-bottom: 0.75rem; }}
  a {{ color: var(--accent); text-decoration: none; }}
  code {{
    background: #0f172a; border: 1px solid var(--border);
    border-radius: 4px; padding: 0.1em 0.4em;
    font-family: "SF Mono", Menlo, monospace; font-size: 0.87em;
  }}
  pre {{
    background: #0a1628; border: 1px solid var(--border);
    border-radius: 8px; padding: 1rem; overflow-x: auto; margin: 1rem 0;
  }}
  pre code {{ background: none; border: none; padding: 0; }}
  table {{
    width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem;
    border: 1px solid var(--border); border-radius: 8px; overflow: hidden;
  }}
  th {{
    background: #1e3a5f; color: var(--accent);
    padding: 0.6rem 1rem; text-align: left; font-weight: 600;
    border-bottom: 1px solid var(--border);
  }}
  td {{ padding: 0.55rem 1rem; border-bottom: 1px solid var(--border); }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: rgba(56, 189, 248, 0.04); }}
  ul, ol {{ padding-left: 1.5rem; margin-bottom: 0.75rem; }}
  li {{ margin-bottom: 0.3rem; }}
  blockquote {{
    border-left: 3px solid var(--accent); padding-left: 1rem;
    color: var(--muted); margin: 1rem 0;
  }}
  hr {{ border: none; border-top: 1px solid var(--border); margin: 2rem 0; }}
  .generated {{
    text-align: center; color: var(--muted); font-size: 0.8rem;
    margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
  }}
</style>
</head>
<body>
<div class="container">
  <div class="banner">
    <div class="banner-icon">☁️</div>
    <div>
      <h1>AWS Cloud Cost Optimization Report</h1>
      <p>Generated {date.today().strftime("%B %d, %Y")} &nbsp;·&nbsp; Powered by DeepAgents + Claude on Bedrock</p>
    </div>
  </div>
  {body}
  <p class="generated">Generated by AWS Cloud Cost Advisor · {date.today().isoformat()}</p>
</div>
</body>
</html>"""

    out = _run_dir() / "report.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    return f"HTML report saved to {out.resolve()}"
